version: '3.8'

services:
  dieti-estates-app:
    build: .
    ports:
      - "9094:9094"
    stdin_open: true
    tty: true
    depends_on:
      - database
    environment:
      DATABASE_URL: "jdbc:postgresql://database:5432/DietiEstates"
      DATABASE_USER: "neondb_owner"
      DATABASE_PASSWORD: "J7DVYAX3kjqB"
      DATABASE_SSL_MODE: "require"
    volumes:
      - /c/Users/Utente/Desktop/:/app/uploads

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: DietiEstates
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: J7DVYAX3kjqB
    ports:
      - "5432:5432"

