services:
  dieti-estates-app:
    build: .
    ports:
      - "9094:9094"
    stdin_open: true
    tty: true
    depends_on:
      - database
    environment:
      DATABASE_URL: "jdbc:postgresql://database:5432/DietiEstates"
      DATABASE_USER: "neondb_owner"
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL_MODE: "require"

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: DietiEstates
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"



